### ISSUE TITLE
Noob question...

### ISSUE THREAD

**Issue by Qile0317** [FlansMods/FlansMod#1044]
Hey all... I am extremely noob but how do I use the 5.6 beta flans mod? I'm new to this and I have no idea what "repository" or "build" means. Do I have to download something else? Thank you! Also I am aware that I am not supposed to be posting this here either. I'm sorry I just want to have some fun :(

**Comment by Liruxo** [comment]
There is nothing wrong with asking a question, it is just the Issues section is supposed to be for Issues but i actually also don't really know a better way to get support. (And really, this is kinda a issue)

Concerning the actual question, you just head over to https://github.com/FlansMods/FlansMod/releases click on "Assets" and download the .jar and put it in your mods folder. (I guess you are familiar with forge modding)
To get some content you have to download the content packs you like (Also available under the "Assets") and drop them into the "Flan" folder

Additionally, at this point in time i would rather use v5.6-beta.3, not  v5.6-beta.5 since vehicle weapons are currently broken in the newer pre-releases.

**Comment by Qile0317** [comment]
Thank you so much! I'll delete this post soon as I realize this is clogging up the issues section. :)
