### ISSUE TITLE
Problem with mode Flan's mod and Dragon API [Minecraft 1.7.10]

### ISSUE THREAD

**Issue by demycat** [FlansMods/FlansMod#1054]
Hi, I have a problem with crafting in Flan's mod. After installing the Dragon API, all Redstone Repeater were replaced with tile.diode.name, how to fix it?

Screenshots
![2019-05-13_21 15 33](https://user-images.githubusercontent.com/34833284/57684266-1e4e2b00-763e-11e9-859a-5d5dab6e4633.png)
![2019-05-13_21 15 35](https://user-images.githubusercontent.com/34833284/57684283-273efc80-763e-11e9-80ba-f1255abec669.png)
![2019-05-13_21 15 38](https://user-images.githubusercontent.com/34833284/57684295-2c03b080-763e-11e9-9f35-7113677090af.png)

Versions :
 - Forge: forge-1.7.10-10.13.4.1614-1.7.10
 - Flan's Mod: Flans Mod-1.7.10-4.10.0

**Comment by Liruxo** [comment]
Flans Mod for 1.7.10 is no longer supported. Please use a newer version of the mod, available at https://github.com/FlansMods/FlansMod/releases

PS: This is most likely not a problem associated in any way with FlansMod, since FlansMod registers the recipe with the normal vanilla repeater and therefore no change in FlansMod would fix the problem.
