### ISSUE TITLE
Flans Mod still crashes when I spawn in a vehicle

### ISSUE THREAD

**Issue by mmol82** [FlansMods/FlansMod#1063]
**To Reproduce**
Steps to reproduce the crash:
1. Spawn Vehicle
2. 
3. 
4. 

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2 - 14.23.5.2838
 - Flan's Mod: 1.12.2-5.6

**Additional context**
 https://gist.github.com/mmol82/d64315b21ceff58a6730ff833b8ccd53

**Comment by mmol82** [comment]
And yes, I updated it from last time I got a crash. Same issue.

**Comment by ChrisLane** [comment]
What content packs do you have installed? Also, somehow I don't see Flan's Mod in your mods list in the crash log.

**Comment by mmol82** [comment]
That's weird. I have it installed. I only have the modern warfare. I can show my files if I have to.

**Comment by mmol82** [comment]
I can equip AK47s, and guns, and armor, but just not spawn vehicles.

**Comment by ChrisLane** [comment]
I suspect that's the issue then. The modern warfare pack requires the simple parts pack to also be installed.

**Comment by mmol82** [comment]
Thank you for responding, but I already tried this. It still doesn't work.

**Comment by mmol82** [comment]
I legitimately think it's an issue with the mod itself. I have followed every instruction. Every thing I downloaded is up to date, it should not be doing this.

**Comment by Liruxo** [comment]
Whatever vehicle you are trying to spawn in has no engine (Or at least the data has none). This is caused by the failing attempt to load the specific part from the NBTCompound of the ItemStack you are holding. This means: A: you have a broken item or B: you are missing the part your vehicle is referencing as engine.

I am not able to reproduce your issue, here a list of things i have done to get it working for me:
1. Download forge and install it
2. make sure you either use a different directory than the default one or delete it beforehand
3. start minecraft once and close it
4. put the downloaded FlansMod.jar into the "mods" folder
5. start minecraft once and close it
6. put the SimpleParts and the ModernWarfare Content Pack into the "Flan" folder
7. Start minecraft
8. generate a new world
9. "it just works" - Jen-Hsun Huang

And not related to any of this: Your crash report is cut of, that's why flans mod is not on the list

**Comment by mmol82** [comment]
Sorry, I went off for a while. Trying now.

**Comment by mmol82** [comment]
Just worked. Thank you!

**Comment by MrRedstoneA1** [comment]
Sorry to leave a comment on a closed issue, but the fix doesn't always seem to work. I fixed the crash by deleting the META-INF folder. If anyone else is still having crashes, try this. It is located in the flan's mod jar, you'll have to open it with a program like winRAR.

**Comment by ShadowBladeYT** [comment]
I think because of your flan pack you need to install all mod pack in the flans file beacuse if you dont it well crash

**Comment by ShadowBladeYT** [comment]
just watch these tutorial https://www.youtube.com/watch?v=S5_GT4m--OE
