### ISSUE TITLE
Flans Mod 5.5.2 Crash

### ISSUE THREAD

**Issue by TheKr4k3n** [FlansMods/FlansMod#1074]
**To Reproduce**
Steps to reproduce the crash:

1. Open Minecraft Launcher
2. Press Play
3. Wait for it to load
4. Crash when loading Flans Mod

**Screenshot**
![Minecraft Crash log](https://user-images.githubusercontent.com/38116019/60916211-d3c2e680-a25b-11e9-8928-ba6e5618dde0.png)

**Versions (please complete the following information):**
 - Forge: 1.12.2-14.23.5.2838
 - Flan's Mod: 5.5.2

**Additional context**

I have no idea what is wrong. I've tried loading Minecraft with just flans mod installed and it crashes. Minecraft only works when I uninstall flans mod. I have 1.12.2 content packs. I don't think any of these mods are incompatible with flans, however, I could be wrong. I also do believe that I have the latest version of forge.

**Comment by Liruxo** [comment]
Please paste your Crashlog into gist (https://gist.github.com/) and paste the link to it into the crash report, since usually its not possible to fix the crash without the complete log. Anyways, i can see you are using an old, no longer supported version. Please head over to https://github.com/FlansMods/FlansMod/releases and download v5.6-beta.3, which should fix the problem. You also need to replace the content packs with their new versions.

**Comment by TheKr4k3n** [comment]
> Please paste your Crashlog into gist (https://gist.github.com/) and paste the link to it into the crash report, since usually its not possible to fix the crash without the complete log. Anyways, i can see you are using an old, no longer supported version. Please head over to https://github.com/FlansMods/FlansMod/releases and download v5.6-beta.3, which should fix the problem. You also need to replace the content packs with their new versions.

So I download v5.6-beta.3 or v5.6-beta.4? And are you sure that they're not up to date? I thought that they were.

**Comment by ChrisLane** [comment]
> So I download v5.6-beta.3 or v5.6-beta.4? And are you sure that they're not up to date? I thought that they were.

We can't help without the crash log.
