### ISSUE TITLE
Shaders graphical bug [1.12.2]  5.6

### ISSUE THREAD

**Issue by RobertMuldoon** [FlansMods/FlansMod#1075]
_Transparent blocks_ such as glass, water, slimeblocks, etc appear through the ground when holding any gun.

This seems to be an incompatibility with Optifine, as I then ran my client without the Optifine.jar, with the other mods + flans.  No graphical bug occurred. 

This bug although bandaided by turning OFF any type of shaders in Optifine is quite annoying as you have to choose between using Flans, or Optifine in the latest versions. I can open an issue with Optifine, but I believe they will direct me to contact any Flan's Mod developers as it is their mod that is incompatible with Optifine, etc. 

Anyway, thank you.

**Screenshots**
![2019-07-10_12 27 18](https://user-images.githubusercontent.com/52754898/60988583-e697f280-a311-11e9-8331-f827067b3f2d.png)
![2019-07-10_12 28 03](https://user-images.githubusercontent.com/52754898/60988584-e697f280-a311-11e9-852f-45f9e3154930.png)

**Versions:**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2838
 - Other Mods:
Xaeros_Minimap_1.17.3_Forge_1.12
XaerosWorldMap_1.4_Forge_1.12
**OptiFine_1.12.2_HD_U_E3**

- Flan's Mod: Flan.s.Mod-1.12.2-5.6
- Flan folder: All content packs released with 5.6

**Comment by Liruxo** [comment]
Pretty sure that this caused by FlansMod, but i have no idea why or how. Currently there are two other Open Issues #888 and #932, related to shader incompatibility.

Im currently looking into #959 and #1046, which also seems to be caused by a similar problem, but as these are problems require a lot of testing it will take some time.
