### ISSUE TITLE
Stack overflow firing gun with Malisis core mod

### ISSUE THREAD

**Issue by Sonic1305** [FlansMods/FlansMod#1145]
_original_
We got a strange Flan's Mod issue when shooting a normal gun. Sometimes it works, sometimes it crashes with a raytrace error. We thought it could be related to a shield (which prevents gun shooting) but even without a shield it crashes on one day, but maybe not on the other. Could be some incompatibility. If you want to try to reproduce it, we are playing the "Extended Reality: No Limits" modpack (Technic Launcher).
Here is my crash log: https://gist.github.com/Sonic1305/a1428c72ff096ea3faa2331e91f3b885

<hr>

_new_
**Describe the bug**
When attempting to fire any of the tanks, the shell either explodes in the players face or it doesn't fire at all. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter any of the tanks
2. Load a tank shell and attempt to fire.

**Expected behaviour**
Disabling of Malisis' Core and Doors causes correct behaviour in the form of the shot firing, hitting and destroying a target.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2838
 - Flan's Mod: tested with 5.5.2 and up, including beta version 7  
 - Malisis Doors: 1.12.2-7.3.0
 - Malisis Core: 1.12.2.6.5.1

**Additional context**
Link to the [issue](https://github.com/Ordinastie/MalisisDoors/issues/283) at MalisisDoors
Edited crashlog in a [gist](https://gist.github.com/Liruxo/58495c790e3468a06ce2b5ebca3bd57e) for better readability

**Comment by ChrisLane** [comment]
I suspect that this is because of this line:
https://github.com/FlansMods/FlansMod/blob/7a0b65e64ebb8d72c3cbe0717b6b285fd568fa43/src/main/java/com/flansmod/common/guns/raytracing/FlansModRaytracer.java#L202
When `getBlockPenetrationDecrease` returns 0 and so an infinite loop is created.
Or perhaps that line is never reached because someone has given a bullet speed of 0 for some reason and so the position never changes.

We should set a minimum for the return of this method. What block are you firing at when you experience the crash? Does the crash always occur when you fire at this block?

**Comment by RedBusters** [comment]
My game is crashing too while firing. the crash report is just spamming "at com.flansmod.common.guns.raytracing.FlansModRaytracer.raytraceBlock(FlansModRaytracer.java:207)". this occurs only while in another dimension

**Comment by Dutchkills** [comment]
My server crashes when i fire in the air, on blocks its fine but when i fire one bullet in the air then within 10 seconds its crashes

**Comment by shivachirr** [comment]
any chance for a fix soon due to 5.5.2 is causing issues that is fixed in all the betas

**Comment by ChrisLane** [comment]
Edited the description to contain more details.

**Comment by ChrisLane** [comment]
Crash fixed in e2a32b52da9059a0dcf89220a1e18bbb3316ad0a
This will also fix a bug where players would be able to increase their bullet penetration range by firing through invincible blocks.

In the end, this comes down to Malisis mods doing something weird, I took a look at the list of issues on their repo and they have a bunch of bounding box related stuff that could be broken.

**Comment by Mortivarus** [comment]
Fix solved the issue of guns not firing, only issue remaining is that shots fired from tanks still explode in your face. However that's then probably caused by bounding issues I suppose.

**Comment by Raptor22a** [comment]
> Fix solved the issue of guns not firing, only issue remaining is that shots fired from tanks still explode in your face. However that's then probably caused by bounding issues I suppose.

Is there any possibility of some sort of fix? It seems that you closed this without really anything being changed. I wish I could offer more technical advice however I'm still barely even a novice when it comes to minecraft modding (I have modding experience with other games like KSP, but that doesn't really carry over).

**Comment by Mortivarus** [comment]
Well the issue seems to be caused by Malisis core/doors, and their developer has gone MIA it seems, so unless you know to fix those issues...
________________________________
