### ISSUE TITLE
the crash games as soon as a vehicle is put down (5.6.0-beta.6)

### ISSUE THREAD

**Issue by ulyssedu45** [FlansMods/FlansMod#1189]
Steps to reproduce the crash:
1.  start game
2. place vechicle

**Versions (please complete the following information)**
 - Forge: forge-1.12.2-14.23.5.2847
 - Flan's Mod: 5.6.0-beta.6
 - WW2-Content.Pack-1.12.2-5.6.0-beta.6
**Crash Log**
[gist](https://gist.github.com/ulyssedu45/44bd8812097d016da7c5acf1883e073b)

**Comment by Liruxo** [comment]
I am unable to reproduce these results.
Please verify you are using the latest content packs and FlansMod jar. If the issue persists it is recommended to use a fresh minecraft installation to rule out outdated or faulty jars and/or configuration files
Please also verify you are following [these steps](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) to install FlansMod, if not note the differences to your process

**Comment by ulyssedu45** [comment]
no work

**Comment by Liruxo** [comment]
The answer "no work" is in no way helpful and does not help me or anyone else. I asked multiple questions, of which none can be answered with "no work". I want to help you but if you do not want to cooperate, i am not willing to spend more time on this

Technical note: This crash seems to be created because the vehicle is missing a engine. But without reproducibility, this is speculation

**Comment by ulyssedu45** [comment]
I launch the games in creative, I take a vehicle in the creative inventory, I place it and the crash games.

this is the latest version of forge and mod (this is the only mod to install)

**Comment by ChrisLane** [comment]
The 'Simple Parts Pack' is a dependency of the 'WW2 Pack', do you have this installed?
