### ISSUE TITLE
upon placing vehicles game/server will crash

### ISSUE THREAD

**Issue by DJGull7** [FlansMods/FlansMod#1221]
**To Reproduce**
Steps to reproduce the crash:
1.  install version 5.5.2 on either server or client
2.  launch pack as normal, close pack, import *any* content pack with vehicles.
3.  launch pack again, go into either server or single player world.
4. place *any* vehicle
5. crash

**Screenshots**

**Versions (please complete the following information)**
 - Forge:  ***any***  (latest, but we used a different version on the server and it still crashed)
 - Flan's Mod:  5.5.2

**Crash Log**

could not find crash logs
**Additional context**

crash thingy at launcher says "tick entity error" or something like that

EDIT:
found similar issue but this was on a different version of forge and the mod, and also happened on a server
https://github.com/FlansMods/FlansMod/issues/1189

**Comment by DJGull7** [comment]
could it be possible to remove the vehicles from the code, and rebuild the mod?
i am trying to host a "public" server for a LARGE discord server, and i would like my server not to crash when ever someone placed a tank or plane or PAK40
 
EDIT: ah it seems you can remove the folders from all the content packs and rebuild them, dont know  if this would cause errors, still, a fix would be better, i would like to blow up my friends base  a t-35

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version

Additionally, if you experience a crash there is a crash log. So if you still experience crashes on the most recent version, please look for an tutorial on how to find it and open a new crash report because "crash thingy at launcher says "tick entity error" or something like that" is no help at all

**Comment by DJGull7** [comment]
ah, i used the most recent version displayed on the website: https://flansmod.com/

**Comment by DJGull7** [comment]
okay so updated to new version (v5.6-beta.7) and everything works great now!
