### ISSUE TITLE
How to install Flan on a server?

### ISSUE THREAD

**Issue by Raptor1818** [FlansMods/FlansMod#1252]
Hello I want to install Flan's Mod (with the content packs) on my 1.12.2 server. I've been trying for quite a while but nothing, the server doesn't start. Please send a video link or explain to me how to do this

**Comment by Liruxo** [comment]
This guide should also been applicable to servers too, as long as you perform the actions with the server and not the minecraft client: https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod

However this seems like a general problem with your forge server, so please make yourself familiar with the process of installing mods onto a forge minecraft server first

If you have further trouble, i will need you to create a bug report where you fill out the template and describe in detail which steps you take and provide more information on what works and what does not. The problem "server doesn't start" can be caused by a million different problems

**Comment by Raptor1818** [comment]
> The problem "server doesn't start" can be caused by a million different problems

Ok I managed to install the mod on the server but I can't load a custom map because of missing files (?)
If you could look at the log and tell me whats happening I would appriciate it. https://paste.shock
Duplicate of #byte.com/kolurabizirejarefaqa
Meanwhile I'll try to reinstall forge and other things
