### ISSUE TITLE
Soviet Flan`s Mod 1.12.2 problem

### ISSUE THREAD

**Issue by WholeaseFight124** [FlansMods/FlansMod#1292]
I know that Soviet Flan`s mod might not be the real Flan`s mod so please tell me if I have no right to submit Soviet Flan`s mod bugs and problems
**Describe the bug**
So,I was testing out the Soviet Flan`s mod,trying to enable some nice russian cars.But when I try spawning such,they become invisible.Simple Parts Pack is installed.Watch the screenshot.

**Screenshots**

![image](https://user-images.githubusercontent.com/71653925/93787504-3b830880-fc39-11ea-8179-40b873db58dc.png)
![image](https://user-images.githubusercontent.com/71653925/93787731-4b9ae800-fc39-11ea-96ef-78beb95bb54d.png)

Mod list:
![image](https://user-images.githubusercontent.com/71653925/93787988-5ce3f480-fc39-11ea-8b5a-65189ff950fd.png)
![image](https://user-images.githubusercontent.com/71653925/93788078-640b0280-fc39-11ea-8ebc-a68f8284f3d3.png)

**Comment by ChrisLane** [comment]
I recommend you try the latest version of the mod https://github.com/FlansMods/FlansMod/releases since your version is very outdated.

I think the invisibility issue is most likely due to the content pack or other mods.
I recommend trying without other mods and then if the issue persists, report the issue to the content pack creator.
