### ISSUE TITLE
I am crashing while trying to put some planes...

### ISSUE THREAD

**Issue by JasonSea1** [FlansMods/FlansMod#632]
http://paste2.org/2ZD84jMt

Help me with that please... Not all of the planes are crashing but some did.

**Comment by keenerb** [comment]
I'm seeing a similar error with some cars:

[B#274]  [17:23:57] [Server thread/ERROR]: Encountered an unexpected exception
[B#274]  net.minecraft.util.ReportedException: Ticking memory connection
[B#274]  	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
[B#274]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
[B#274]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[B#274]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
[B#274]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#274]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#274]  Caused by: java.lang.NullPointerException
[B#274]  	at com.flansmod.common.driveables.EntityWheel.initPosition(EntityWheel.java:47) ~[EntityWheel.class:?]
[B#274]  	at com.flansmod.common.driveables.EntityWheel.<init>(EntityWheel.java:42) ~[EntityWheel.class:?]
[B#274]  	at com.flansmod.common.driveables.EntityDriveable.initType(EntityDriveable.java:142) ~[EntityDriveable.class:?]
[B#274]  	at com.flansmod.common.driveables.EntityVehicle.initType(EntityVehicle.java:72) ~[EntityVehicle.class:?]
[B#274]  	at com.flansmod.common.driveables.EntityVehicle.<init>(EntityVehicle.java:66) ~[EntityVehicle.class:?]
[B#274]  	at com.flansmod.common.driveables.ItemVehicle.func_77659_a(ItemVehicle.java:136) ~[ItemVehicle.class:?]
[B#274]  	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
[B#274]  	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) ~[mx.class:?]
[B#274]  	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
[B#274]  	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
[B#274]  	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
[B#274]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[B#274]  	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
[B#274]  	... 5 more

**Comment by Ianaver** [comment]
I had the same thing except it was "ticking entity"

pastebin: http://pastebin.com/7WjbZ5wc
