### ISSUE TITLE
Explosion differently damage blocks in water, depending on Direction

### ISSUE THREAD

**Issue by ruyak0402** [FlansMods/FlansMod#640]
Explosion differently damage blocks in water, depending on direction.
Check this video: https://www.youtube.com/watch?v=H5CzZZTBVj4
in the video, signs tell which direction is, also you can check it on the minimap.
From North, West - DO damage blocks
From South, East - DO NOT damage blocks

**Comment by BlackJack55** [comment]
this might be due to the coordinates the entity gives the FlansModExplosion. Are those rounded up/down since it only appears in 2 directions, but only in the opposite ones? using exact values should fix that, the new way of the explosions however should not be causing this.

Kind regards,

BlackJack55
