### ISSUE TITLE
1.7.10 Modern Weapons Content Pack causing slow World load

### ISSUE THREAD

**Issue by Gamerbolts** [FlansMods/FlansMod#830]
Hi I am having a really interesting issue. I have a modpack and server and when I load the server without modern weapons it loads in 3 minutes about. with the modern weapons content pack it takes about 13 minutes to load ... Not sure why or what is going on here or if there is any way to fix this. Any help is appreciated. Thank you!

**Comment by PrototypeTheta** [comment]
That could be my massive texture files on the tanks. I'll see if I can cut them down.

Though I must say that I've never seen this cause a delay on that scale, usually it's only a few seconds more.

**Comment by E-Block** [comment]
I'm having the same issue with 1.7.10, and it goes away if I remove the modern weapons pack. I'm using MultiMC and when I look at the console while its loading, the bulk of the loading time is taken by loading in dimensions. This is happening in singleplayer too, and for me it only happens when loading into a world that has been previously made; when creating new worlds, this problem doesn't happen.

**Comment by border999** [comment]
Same issue here, I think I tracked the issue back to the fact that a few lines of errors involving missing textures are spammed during client and world load-up. Spams the three lines every time another dimension is loaded at start-up, when you have a lot of mods that add dimensions this significantly increases load time.
I hope this is helpful.

**Comment by border999** [comment]
I'm sure quite a few people have complained about three certain gun textures spamming that they're missing.

**Comment by Coll1234567** [comment]
Is there any fix for this? Even with no errors spammed during world load and without the modern warfare content pack I am still facing 5+ seconds to load each dimension, whereas it normally happens almost instantly.
