### ISSUE TITLE
Shaders/Optifine Compatibility 

### ISSUE THREAD

**Issue by alexdecoder** [FlansMods/FlansMod#888]
When using shader's packs with the flans mod, the graphics are completely screwed up. However, when you disable them, it's completely fine.
![2018-03-10_13 10 30](https://user-images.githubusercontent.com/10868929/37245343-8ef6355a-2464-11e8-8d2e-475863652285.png)
![2018-03-10_13 10 58](https://user-images.githubusercontent.com/10868929/37245344-90057032-2464-11e8-940c-935f2f28e57e.png)
![2018-03-10_13 11 02](https://user-images.githubusercontent.com/10868929/37245345-9144ca2e-2464-11e8-9f76-e653b72532de.png)

When you hold the Humvee, everything goes transparent, but when you choose something else, it goes back to normal

Optifine: HD C5 Ultra w/ Kuda Shaders pack v6.2.81

Minecraft: 1.12.2 w/ Forge 14.23.2.2624

Flans: 5.5.2

**Comment by ArtsicleOfficial** [comment]
yea, would be cool if this was fixed

**Comment by Fexcraft** [comment]
https://github.com/FlansMods/FlansMod/blob/b1c0c44e75ac2a448e98358ec5690ce439ae1f74/src/main/java/com/flansmod/client/model/RenderVehicle.java#L236

**Comment by NightScale5755** [comment]
anyone find a fix?

**Comment by Trackhe** [comment]
we need a fix.

**Comment by TheOnly8Z** [comment]
This bug seems to persist despite a similar issue being closed.

Used:

- Minecraft 1.12.2

- Flan's Mod 5.5.2

- Optifine HD U E5

- Slidur's Enhanced Default v1.10 shaderpack

- OpenGL 4.6.0 NVIDIA 430.86

- GeForce GTX 1070

![2020-03-19_20 13 42](https://user-images.githubusercontent.com/13565172/77126113-5d979600-6a1e-11ea-9313-3df3cf6549d6.png)
![2020-03-19_20 13 32](https://user-images.githubusercontent.com/13565172/77126114-5e302c80-6a1e-11ea-9c30-bb216c0e7654.png)
![2020-03-19_20 21 51](https://user-images.githubusercontent.com/13565172/77126430-63da4200-6a1f-11ea-8add-e41a2a202ee4.png)

**Comment by ChrisLane** [comment]
@TheOnly8Z you're usinn an old version of the mod.
https://github.com/FlansMods/FlansMod/releases
