### ISSUE TITLE
[1.12.2]Applied energistics 2 compatability issue(crash)

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#903]
Since i added flans to my modpack applied energistics 2 crashes on startup.
Crash report: https://www.dropbox.com/s/c7mh3gavhibn4vt/crash-2018-04-27_17.22.01-client.txt?dl=0
Applied energistics 2 version: appliedenergistics2-rv5-stable-11

**Comment by ChrisLane** [comment]
This looks to be a problem with Applied Energistics trying to statically register dimension IDs and failing because another mod has already done that.

Flan's Mod registers dimension IDs dynamically to avoid conflicts like this and so is not to blame:
https://github.com/FlansMods/FlansMod/blob/1.12.2/src/main/java/com/flansmod/apocalypse/common/FlansModApocalypse.java#L198

**Comment by ghost** [comment]
i suggest you let it use another dimension ID by default, there are plenty of unused ones

**Comment by ChrisLane** [comment]
@TomTheHero I suggest you look at the link I gave.
See "getNextFreeDimId()"? That's exactly what that does.

**Comment by ghost** [comment]
I ment that you set a new default one it starts searching at(like dim10) or so as that will decrease the likelyhood of issues such as this occuring again.

**Comment by timpan77** [comment]
how to edit flans mod/config ?
