### ISSUE TITLE
JourneyMap hides when entering a plane

### ISSUE THREAD

**Issue by Turakar** [FlansMods/FlansMod#936]
I am unsure where to post this, but if I enter a plane, JourneyMap hides away. However, a map during flight would be of great help. Is there something I can do about this?

Version: 5.5.2
MC: 1.12.2
JourneyMap: 5.5.2
Java: 1.8
Default settings

**Comment by christopher0936** [comment]
I also noticed this. Its quite irritating as exploration by air was my entire idea behind adding the mod to my personal pack.

**Comment by ChrisLane** [comment]
@christopher0936 I don't have a solution to the minimap issue in question I'm afraid, but I can tell you that controls for other mods while in vehicles were fixed in "recent" commits that are not in the current released version. This would allow you to bring up the fullscreen map while in a vehicle.

**Comment by Turakar** [comment]
OK, thats a workaround. It would be interestingto know, if other overlays hide, too. I currently do not remember one...

**Comment by Turakar** [comment]
Thank you!
