### ISSUE TITLE
[1.12] server message about bad seat data and killing wheel

### ISSUE THREAD

**Issue by mensreaMC** [FlansMods/FlansMod#974]
I noticed this printout in the server log: 

25.11 23:15:56 [Server] Server thread/WARN [flansmod]: Killing wheel due to invalid type tag 
25.11 23:15:56 [Server] Server thread/WARN [minecraft/Chunk]: Wrong location! (548, 74) should be (547, 74), EntityWheel['entity.Wheel.name'/1676140, l='Arkansas', x=8768.98, y=64.00, z=1186.80] 
25.11 23:15:56 [Server] Server thread/WARN [flansmod]: Killing wheel due to invalid type tag 
25.11 23:15:56 [Server] Server thread/WARN [minecraft/Chunk]: Wrong location! (548, 74) should be (547, 74), EntityWheel['entity.Wheel.name'/1676141, l='Arkansas', x=8768.68, y=64.00, z=1184.57] 
25.11 23:15:56 [Server] Server thread/WARN [flansmod]: Killing wheel due to invalid type tag 
25.11 23:15:56 [Server] Server thread/WARN [flansmod]: Killing wheel due to invalid type tag 
25.11 23:15:56 [Server] Server thread/WARN [minecraft/WorldServer]: Keeping entity flansmod:wheel that already exists with UUID 1dd81230-e10e-441b-bca6-5087abfec09a 
25.11 23:15:56 [Server] Server thread/WARN [minecraft/WorldServer]: Keeping entity flansmod:wheel that already exists with UUID 1b576ab7-dd8a-41ce-beae-6ed5feb3c590

Sounds ominous. Both wheel and seat parts have the correct tags afaik.

**Comment by joanros97** [comment]
Same problem on my server. I have a 7.1.0 Sponge server with Flans mod 5.6 and I'm getting the same error.
And yes, I've disabled the "max-speed" setting on the Sponge config that was causing that players fall from the planes and displayed the same exact message, but I'm still getting this anoying message that also causes a lot of lag on the server

"[flansmod]: Killing wheel due to invalid type tag" this message is spamed on the server log every few seconds and is creating insane lag. Please help!
